# Generated by Django 4.1.1 on 2022-10-18 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroomapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherlogin',
            name='subject',
            field=models.CharField(choices=[('SP', 'SP'), ('DCS', 'DCS'), ('DBMS', 'DBMS'), ('MATHS', 'MATHS'), ('MBD', 'MBD'), ('ENGLISH', 'ENGLISH')], max_length=30),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('complaint', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('reply', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
