# Generated by Django 4.1.1 on 2022-10-21 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroomapp', '0004_alter_teacherlogin_subject_taddasgnmnttopic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherlogin',
            name='subject',
            field=models.CharField(choices=[('MATHS', 'MATHS'), ('SP', 'SP'), ('ENGLISH', 'ENGLISH'), ('MBD', 'MBD'), ('DBMS', 'DBMS'), ('DCS', 'DCS')], max_length=30),
        ),
        migrations.CreateModel(
            name='SaddAssignments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
