# Generated by Django 4.1.1 on 2022-10-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroomapp', '0005_alter_teacherlogin_subject_saddassignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='saddassignments',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='teacherlogin',
            name='subject',
            field=models.CharField(choices=[('MATHS', 'MATHS'), ('SP', 'SP'), ('DBMS', 'DBMS'), ('ENGLISH', 'ENGLISH'), ('MBD', 'MBD'), ('DCS', 'DCS')], max_length=30),
        ),
    ]
